[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ['@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/', 
'@chainlink/local/=lib/chainlink-local/', '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/']

[fuzz] 
runs = 10000

[Invariant]
runs = 100
depth = 128
fail_on_revert = true

[rpc_endpoints]
ETH_MAINNET_RPC_URL="https://eth-mainnet.g.alchemy.com/v2/Xw8PCp_3hHh_MOBnHUy6J"
SEPOLIA_RPC_URL="https://eth-sepolia.g.alchemy.com/v2/Xw8PCp_3hHh_MOBnHUy6J"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
